mrs_uav_controllers:

  emergency_controller:

    mpc:

      mpc_model:

        number_of_states: 3

        dt1: 0.01
        dt2: 0.05

      mpc_parameters:

        horizon_length: 26

        horizontal:

          Q: [500, 100, 100] # state error penalization
          S: [1000, 300, 300] # last state error penalization

          max_speed: 10.0 # hight velocity to allow smooth stopping from high speeds
          max_acceleration: 2.5 # this should be slightly lareget than the acceleration in the landoff_tracker
          max_jerk: 10.0

        vertical:

          Q: [100, 10, 10] # state error penalization
          S: [100, 10, 10] # last state error penalization

          max_speed: 10.0 # hight velocity to allow smooth stopping from high speeds
          max_acceleration: 2.5 # this should be slightly lareget than the acceleration in the landoff_tracker
          max_u: 10.0

      solver:

        verbose: false
        max_iterations: 30

    so3:

      rampup:
        enabled: true
        speed: 0.75 # [1/s]

      mass_estimator:
        km: 0.5 # [kg/s], mass estimator max rate
        km_lim: 5.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

        fuse_acceleration: false

      gain_filtering:

        rate: 10.0 # [Hz]

        perc_change_rate: 1.0
        min_change_rate: 0.2 # perc of the difference

        # gains can be muted by the tracker by this factor
        # gains are also muting just after activation
        gain_mute_coefficient: 0.5

      # saturations and limits
      constraints:

        throttle_saturation: 0.9 # [-], range from 0 to 1

        # When the controller wants to output tilt larger than this,
        # it will return an empty command instead, which should trigger
        # a failsafe in the control manager.
        tilt_angle_failsafe:
          enabled: true
          limit: 90.0 # [deg]

      angular_rate_feedforward:

        # jerk feed forward
        jerk: true

      # preferred output mode:
      # - choose this one if more output modes are available
      preferred_output: 2 # {0 = actuators,
                          #  1 = control_group,
                          #  2 = attitude_rate,
                          #  3 = attitude,}
                          #
      gains:

        integral_gains:

          kiw: 0.1
          kib: 0.1

          kiw_lim: 10.0
          kib_lim: 10.0

        attitude:
          roll_pitch: 5.0
          yaw: 1.0

        attitude_rate:
          roll_pitch: 4.0
          yaw: 4.0

    # PID gains for the position controller
    # used only when outputing desired "velocity"
    position_controller:

      translation_gains:
        p: 2.0
        d: 0.15
        i: 0.2
      heading_gains:
        p: 1.0
        d: 0.1
        i: 0.01
